version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456
    ports:
      - "1433:1433"
    networks:
      - app-network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Altere conforme necessário
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
