version: "3.9"
services:
  api:
    build:
      context: .  
      dockerfile: Tech.Test.Payment.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=DB_PAYMENT;User Id=sa;Password=SenhaForte@123;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=SenhaForte@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

